### ISSUE TITLE
Style Site to appear like main OAB site

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/Comms-and-Advocacy#1]
- [x] Fonts
- [x] Color Scheme
- [x] Orange Buttons

**Comment by mtb-za** [comment]
Just to clarify, http://openaccessbutton-righttoresearch.nationbuilder.com/ needs to look like https://openaccessbutton.org/ yes?

**Comment by JosephMcArthur** [comment]
Yes, not pixel for pixel, but approaching it. First things first, just get
the colors straight.

Note: please keep the resizing header, I like it ;)

On 4 January 2016 at 08:48, Martin Bentley <notifications@github.com> wrote:

> Just to clarify,
> http://openaccessbutton-righttoresearch.nationbuilder.com/ needs to look
> like https://openaccessbutton.org/ yes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OAButton/Comms-and-Advocacy/issues/1#issuecomment-168613952>
> .
>



-- 
Joseph McArthur
Assistant Director: Right to Research Coalition
<http://righttoresearch.org/>
Co-Lead/Founder: Open Access Button <http://openaccessbutton.org/>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur
Linkedin <http://linkd.in/1BgZ1jU>

**Comment by mtb-za** [comment]
Have done the colours, generally.

The buttons should also appear orange now. Will look into the fonts next.

**Comment by mtb-za** [comment]
This should be done. Please feel free to reopen it if I have missed something.
