### ISSUE TITLE
Set up team.openaccessbutton.org as the domain

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/Comms-and-Advocacy#10]

**Comment by mtb-za** [comment]
I think that Mark might need to do this one.

http://nationbuilder.com/how_to_connect_a_custom_domain

**Comment by davidecarroll** [comment]
fwiw I purchased teambutton dot something a while ago 

99% sure I could do the domain name changes whatever they are

**Comment by JosephMcArthur** [comment]
Do you prefer teambutton? I'm ambivalent either way. If anything I prefer it as it's oa/od neutral

**Comment by mtb-za** [comment]
I have no preference here either.

In any case, the required steps are in the link above.

**Comment by JosephMcArthur** [comment]
have asked @davidecarroll to use teambutton for now.
