### ISSUE TITLE
Remove "powered by people like you" bar

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/Comms-and-Advocacy#12]

**Comment by mtb-za** [comment]
This is done.

**Comment by JosephMcArthur** [comment]
*dances* I hate that bar, even though I'm sure there is good evidence to
support it being there. Social proof and what not.

On 13 January 2016 at 12:10, Martin Bentley <notifications@github.com>
wrote:

> This is done.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OAButton/Comms-and-Advocacy/issues/12#issuecomment-171273212>
> .
>



-- 
Joseph McArthur
Assistant Director: Right to Research Coalition
<http://righttoresearch.org/>
Co-Lead/Founder: Open Access Button <http://openaccessbutton.org/>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur
Linkedin <http://linkd.in/1BgZ1jU>
