### ISSUE TITLE
Remove tags and like buttons from all page templates

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/Comms-and-Advocacy#13]
it's just unnessasary page faf if you ask me. Should be able to do at the page template level.

**Comment by mtb-za** [comment]
- [ ] basic
- [ ] event
- [ ] volunteer
- [ ] join
- [ ] home
- [ ] calendar pages

**Comment by mtb-za** [comment]
Calendar does not seem to have any by default, but have fixed the rest.

I have left the pages' activity stream intact. Let me know if this is something that we want to have or not.

**Comment by mtb-za** [comment]
For anyone else wanting to do this, remove the following from the templates, if present:

    {% if page.tags_count > 0 %}
      <div class="page-tags">
        {% include "page_tags" with page %}
      </div>
      {% endif %}
    
      <div class="like-page">
        <strong>Do you like this page?</strong>
        {% include "like_page" %}
      </div>

**Comment by JosephMcArthur** [comment]
Sounds like we're good to close then!
