### ISSUE TITLE
Set up footer on new site

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/Comms-and-Advocacy#2]

**Comment by mtb-za** [comment]
This is done. It is not an exact match (no RSS feed, for example), but is fairly close.

Relvant file:
layout.html

Comments? Otherwise I will close.

**Comment by JosephMcArthur** [comment]
Thanks, good to close.

On 13 January 2016 at 12:05, Martin Bentley <notifications@github.com>
wrote:

> This is done. It is not an exact match (no RSS feed, for example), but is
> fairly close.
>
> Relvant file:
> layout.html
>
> Comments? Otherwise I will close.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OAButton/Comms-and-Advocacy/issues/2#issuecomment-171271585>
> .
>



-- 
Joseph McArthur
Assistant Director: Right to Research Coalition
<http://righttoresearch.org/>
Co-Lead/Founder: Open Access Button <http://openaccessbutton.org/>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur
Linkedin <http://linkd.in/1BgZ1jU>
